# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-17 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_local', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_chr', models.IntegerField(null=True)),
                ('length', models.IntegerField()),
                ('name', models.TextField()),
                ('sequence', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('short_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('length', models.IntegerField()),
                ('ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='chromosome',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chromosomes', to='zprapp.Organism'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='chromosome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='zprapp.Chromosome'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='zprapp.AnnotationType'),
        ),
        migrations.AddField(
            model_name='aggregation',
            name='annotation_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregation_slaves', to='zprapp.Annotation'),
        ),
        migrations.AddField(
            model_name='aggregation',
            name='annotation_slave',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_by', to='zprapp.Annotation'),
        ),
    ]
