# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chromosome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start', models.FloatField()),
                ('length', models.FloatField()),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zprapp.Chromosome')),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scaffold',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('length', models.FloatField()),
                ('order', models.IntegerField()),
                ('start', models.FloatField()),
                ('chromosome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zprapp.Chromosome')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('scaffold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zprapp.Scaffold')),
            ],
        ),
        migrations.AddField(
            model_name='marker',
            name='meaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zprapp.Meaning'),
        ),
        migrations.AddField(
            model_name='chromosome',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zprapp.Organism'),
        ),
    ]
