# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-02 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zprapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_local', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_chr', models.IntegerField(null=True)),
                ('length', models.IntegerField()),
                ('name', models.TextField()),
                ('sequence', models.TextField(null=True)),
                ('aggregated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zprapp.Aggregation')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_name', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='marker',
            name='chromosome',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='scaffold',
            name='chromosome',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='scaffold',
        ),
        migrations.AddField(
            model_name='chromosome',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chromosome',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
        migrations.DeleteModel(
            name='Meaning',
        ),
        migrations.DeleteModel(
            name='Scaffold',
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
        migrations.AddField(
            model_name='annotation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zprapp.AnnotationType'),
        ),
        migrations.AddField(
            model_name='aggregation',
            name='annotation_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zprapp.Annotation'),
        ),
    ]
