# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-02 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zprapp', '0002_auto_20170402_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='aggregated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zprapp.Aggregation'),
        ),
    ]
