# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-02 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zprapp', '0003_auto_20170402_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='chromosome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zprapp.Chromosome'),
            preserve_default=False,
        ),
    ]
