# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-18 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zprapp', '0004_annotation_chromosome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chromosome',
            old_name='ordered',
            new_name='order',
        ),
    ]
