# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-18 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zprapp', '0005_auto_20170418_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromosome',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chromosomes', to='zprapp.Organism'),
        ),
    ]
