# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-19 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zprapp', '0006_auto_20170418_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregation',
            name='annotation_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_slaves', to='zprapp.Annotation'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='aggregated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='zprapp.Aggregation'),
        ),
        migrations.AlterField(
            model_name='annotationtype',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
