# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-19 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zprapp', '0008_auto_20170419_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chromosome',
            old_name='order',
            new_name='ordered',
        ),
    ]
