from zpr.database.v3.db_inserter import Inserter
import os

Import('env')

inserter = Inserter()
if env['build_db'] == 1:
    print 'BUILD_DB'
    inserter.insert()
    conf = AppBuilder.load_conf()
    conf['db']['built'] = 1
    AppBuilder.save_conf(conf)

elif env['clear_db'] == 1:
    print 'CLEAR_DB'
    inserter.delete()

